name: 'Terraform Apply'

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/build.yml

  docker_build:
    needs: build
    uses: ./.github/workflows/docker-build.yml

  terraform_plan:
    needs: docker_build
    uses: ./.github/workflows/plan.yml

  terraform_apply_dev:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra/envs/dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::090814039522:role/TerraformRole
          role-session-name: GitHubActions
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Download Terraform Plan
        uses: actions/download-artifact@v5
        with:
          name: tfplan-dev
          path: infra/envs/dev

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve tfplan


  terraform_apply_prod:
    needs: terraform_apply_dev

    runs-on: ubuntu-latest

    environment:
      name: production

    defaults:
      run:
        working-directory: infra/envs/prod

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::090814039522:role/TerraformRole
          role-session-name: GitHubActions
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Download Terraform Plan
        uses: actions/download-artifact@v5
        with:
          name: tfplan-prod
          path: infra/envs/prod

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve tfplan