name: 'Terraform build'

on:
  pull_request:
    branches:
      - main

jobs:
    terraform_build:
        runs-on: ubuntu-latest

        defaults:
          run:
            working-directory: app

        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Setup Python
            uses: actions/setup-python@v5
            with:
                python-version: "3.12"


          - name: Install dependencies
            run: |
                pip install -r requirements.txt


          - name: Lint
            run: |
                ruff check .

          - name: Format check
            run: |
                black --check .

          - name: Tests
            run: |
                pytest

          - name: Package Lambda
            run: |
              zip ../infra/modules/lambda/reader.zip reader.py
              zip ../infra/modules/lambda/lambda.zip lambda.py
    

          - name: Upload artifact
            uses: actions/upload-artifact@v4
            with:
              name: lambda-package
              path: ../infra/modules/lambda/reader.zip

          - name: Upload artifact
            uses: actions/upload-artifact@v4
            with:
              name: reader-package
              path: ../infra/modules/lambda/lambda.zip