name: 'Docker Build and Push'

on:
  workflow_call:

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  docker_build:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::090814039522:role/TerraformRole
          role-session-name: GitHubActions
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push writer Image
        id: build-writer
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/writer:$IMAGE_TAG app/handler
          docker push $ECR_REGISTRY/writer:$IMAGE_TAG

      - name: Build and Push reader Image
        id: build-reader
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/reader:$IMAGE_TAG app/reader
          docker push $ECR_REGISTRY/reader:$IMAGE_TAG

      - name: Build and Push notifier Image
        id: build-notifier
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/notifier:$IMAGE_TAG app/notifier
          docker push $ECR_REGISTRY/notifier:$IMAGE_TAG

      - name: Create terraform image variables
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "writer_image_uri = \"$ECR_REGISTRY/writer:$IMAGE_TAG\"" \
            > infra/envs/dev/image.tfvars
          
          echo "reader_image_uri = \"$ECR_REGISTRY/reader:$IMAGE_TAG\"" \
            >> infra/envs/dev/image.tfvars
          
          echo "writer_image_uri = \"$ECR_REGISTRY/writer:$IMAGE_TAG\"" \
            > infra/envs/prod/image.tfvars
          
          echo "reader_image_uri = \"$ECR_REGISTRY/reader:$IMAGE_TAG\"" \
            >> infra/envs/prod/image.tfvars
          
          echo "notifier_image_uri = \"$ECR_REGISTRY/notifier:$IMAGE_TAG\"" \
            >> infra/envs/prod/image.tfvars
          
          echo "notifier_image_uri = \"$ECR_REGISTRY/notifier:$IMAGE_TAG\"" \
            >> infra/envs/dev/image.tfvars

      - name: Upload image vars
        uses: actions/upload-artifact@v4
        with:
          name: terraform-image-vars-dev
          path: infra/envs/dev/image.tfvars

      - name: Upload image vars
        uses: actions/upload-artifact@v4
        with:
          name: terraform-image-vars-prod
          path: infra/envs/prod/image.tfvars