name: 'Terraform Plan'

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/build.yml

  docker_build:
    needs: build
    uses: ./.github/workflows/docker-build.yml

  terraform_plan:
    needs:
      - docker_build
    strategy:
      matrix:
        env:
          - dev
          - prod

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::090814039522:role/TerraformRole
          role-session-name: GitHubActions
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Checkov
        run: pip install checkov==3.3.8

      - name: Run Checkov
        run: checkov -d .

      - name: Install TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Terraform lint
        run: |
          tflint --init
          tflint

      - name: Download image vars
        uses: actions/download-artifact@v4
        with:
          name: terraform-image-vars
          path: infra/envs/${{ matrix.env }}

      - name: Terraform Init
        working-directory: infra/envs/${{ matrix.env }}
        run: terraform init

      - name: Terraform Validate
        working-directory: infra/envs/${{ matrix.env }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: infra/envs/${{ matrix.env }}
        run: |
          terraform plan \
            -var-file=${{ matrix.env }}.tfvars \
            -var-file=image.tfvars \
            -input=false \
            -no-color \
            -out=tfplan

      - name: Save Plan Output
        working-directory: infra/envs/${{ matrix.env }}
        run: terraform show -json tfplan > plan.json

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v5
        with:
          name: tfplan-${{ matrix.env }}
          path: infra/envs/${{ matrix.env }}/tfplan

      - name: Upload Plan JSON
        uses: actions/upload-artifact@v5
        with:
          name: plan-json-${{ matrix.env }}
          path: infra/envs/${{ matrix.env }}/plan.json